include:
  ################
  # DrupalCI includes:
  # As long as you include this, any future includes added by the Drupal Association will be accessible to your pipelines automatically.
  # View these include files at https://git.drupalcode.org/project/gitlab_templates/
  ################
  - project: $_GITLAB_TEMPLATES_REPO
    ref: $_GITLAB_TEMPLATES_REF
    file:
      - '/includes/include.drupalci.main-d7.yml'
      - '/includes/include.drupalci.variables.yml'
      - '/includes/include.drupalci.workflows.yml'

variables:
  _SHOW_ENVIRONMENT_VARIABLES: 0
  _PHPUNIT_PARAMETERS:
    value: ''
    description: 'Additional parameters for use in PHPUNIT parallel job matrix.'

composer:
  after_script:
    # Third-party modules have been loaded via the projects composer.json into
    # vendor/drupal but they need to be moved into sites/all/modules for D7.
    # Remove when https://www.drupal.org/project/gitlab_templates/issues/3392363 is fixed.
    - ls -lG $CI_PROJECT_DIR/$_WEB_ROOT/sites/all/modules/custom
    - ls -lG $CI_PROJECT_DIR/vendor/drupal
    - cp -LR $CI_PROJECT_DIR/vendor/drupal/* $CI_PROJECT_DIR/$_WEB_ROOT/sites/all/modules
    # The directory vendor/drupal has been copied but must be removed, as this is a duplicate and causes problems.
    - rm -R $CI_PROJECT_DIR/$_WEB_ROOT/sites/all/modules/drupal
    - ls -lG $CI_PROJECT_DIR/$_WEB_ROOT/sites/all/modules

phpcs:
  allow_failure: false

phpunit:
  parallel:
    matrix:
      # Run test classes in parallel.
      - _MATRIX_VALUE:
        - SchedulerFunctionalTest
        - SchedulerDateModuleTest
        - SchedulerRulesTest
        - SchedulerApiTestCase
  variables:
    # Specify the required parameters passed to RUN-TESTS.SH
    _PHPUNIT_EXTRA: --class $_MATRIX_VALUE $_PHPUNIT_PARAMETERS
